project:
  type: book
  output-dir: _book

book:
  title: "Entwurf und Inbetriebnahme einer Testumgebung f체r Klasse-D Leistungsverst채rker"
  author: "C. Ymela-Dega, A. Huber, and M. Meiners"
  date: "04.11.2024"
  reader-mode: true

  page-footer:
    left: |
      Entwurf und Inbetriebnahme einer Testumgebung f체r Klasse-D Leistungsverst채rker
      C. Ymela-Dega, A. Huber und M. Meiners.
    right: |
      This thesis was built with <a href="https://quarto.org/">Quarto</a>.
#  cover-image: images/hsb-logo.png
#  favicon: images/hsb-logo.png
  site-url: https://mimeiners.github.io/class-d-test/
  repo-url: https://github.com/mimeiners/class-d-test/
  repo-branch: main
  repo-actions: [edit, issue]


  chapters:
    - index.qmd

    - part: Front-Matter
      chapters:
        - docs/00_Vorwort.md
    
    - part: Main-Matter
      chapters:
        - docs/01_Einleitung.md
        - docs/02_Stand_der_Technik.md
        - docs/03_Modellbildung.md
        - docs/04_Teststand.md
        - docs/05_Zusammenfassung.md
        - docs/06_Bibliographie.md

    - part: Back-Matter
      chapters:
        - docs/07_Anhang.md
      
bibliography: _bibliography/references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

execute:
  freeze: auto

editor: visual
